#!/bin/bash

command=$1

### Helpers

# IsWorkdirClean - is the workdir clean => no patch in current series applied.
# Returns 0 if workdir is clean
function IsWorkdirClean(){
  if [ -e patches/series ]; then 
    quilt applied &>/dev/null
    if [ $? == 0 ]; then
      echo "Patches applied in this series."
      return 1
    fi
    # no patch applied in this series
    return 0
  fi
  # no series file
  return 0
}

# Add a new series file
function add(){
  name=$1
  :> patches/$name.series
}

# List existing series files
function list(){
  ls -1 patches/*.series
}

# Current active series name
function curr(){
  basename $(readlink -f patches/series) .series
}

# Switch to a different series file
function switch(){
  name=$1
  IsWorkdirClean
  if [ $? == 1 ]; then
      echo "Cannot switch."
      return
  fi
  ln -sf $PWD/patches/$name.series patches/series
}

# Delete a series file by name
function delete(){
  name=$1
  # if currently applied branch
  if [ "$name" == "$(curr)" ]; then
    IsWorkdirClean
    if [ $? == 1 ]; then
	echo "Cannot delete."
	return
    fi
  fi
  rm patches/$name.series
}

# Meta information associated with a series
function meta(){
  name=$1
  if [ "$name" == "" ]; then
    name="$(curr)"
  fi

  $EDITOR patches/$name.meta
}

# pop all patches in the current series
function popall(){
  num_patches="$(quilt applied | wc -l)"
  for((n=0;n<$num_patches;n++)); do quilt pop; done
}

# Gitapply the current series
# Apply and index patches in the current series in order 
function gitapply(){
  IsWorkdirClean
  if [ $? == 1 ]; then
    echo "Cannot involve git now."
    return
  fi
  while read patch; do
    echo "Applying patch $patch:"
    git apply --index patches/$patch
  done < patches/series
}

# Switch the current series using dmenu
function dmenu_switch(){
  switch $(basename $(list | dmenu -l 5) .series)
}

function helpfun(){
  echo "qsm - Quilt Series Manager with additional git related utils"

  echo ""
  echo "Commands: "
  echo "  add <series> - add a new series"
  echo "  list - list all series names"
  echo "  curr - print currently active series"
  echo "  switch <series> - switch to a different series"
  echo "  delete <series> - delete a series"
  echo "  meta <series> - display metafile of the current series"
  echo "  popall - pop all applied patches"

  echo ""
  echo "  git utils"
  echo "    gitapply - apply and index current series"

  echo ""
  echo "  dmenu utils"
  echo "    ds - switch patch using dmenu"
}

if [ "$command" == "add" ]; then
  add $2
elif [ "$command" == "list" ]; then
  list
elif [ "$command" == "curr" ]; then
  curr
elif [ "$command" == "switch" ]; then
  switch $2
elif [ "$command" == "delete" ]; then
  delete $2
elif [ "$command" == "meta" ]; then
  meta $2
elif [ "$command" == "popall" ]; then
  popall
elif [ "$command" == "gitapply" ]; then
  gitapply
elif [ "$command" == "ds" ]; then
  dmenu_switch
else
  helpfun
fi
